import type { SignatureDefinition } from '../types';

export const SIGNATURES: SignatureDefinition[] = [
  {
    id: 'the-bale',
    name: 'The Bale',
    tagline: 'Fresh from the bale. Curated for you.',
    defaultPalette: 'maroon',
    defaultLayout: 'grid-dense',
    defaultTypography: 'editorial',
    defaultCardStyle: 'clean-square',
    defaultSectionOrder: ['section-header', 'section-featured', 'section-grid', 'section-contact'],
  },
  {
    id: 'the-vault',
    name: 'The Vault',
    tagline: 'Rare finds. Locked in.',
    defaultPalette: 'velvet',
    defaultLayout: 'editorial',
    defaultTypography: 'editorial',
    defaultCardStyle: 'polaroid',
    defaultSectionOrder: ['section-header', 'section-hero', 'section-featured', 'section-grid', 'section-contact'],
  },
  {
    id: 'the-atelier',
    name: 'The Atelier',
    tagline: 'Bespoke. Made for you.',
    defaultPalette: 'parchment',
    defaultLayout: 'minimal',
    defaultTypography: 'warm',
    defaultCardStyle: 'minimal-line',
    defaultSectionOrder: ['section-header', 'section-about', 'section-grid', 'section-contact'],
  },
  {
    id: 'the-archive',
    name: 'The Archive',
    tagline: 'Every piece has a story.',
    defaultPalette: 'slate',
    defaultLayout: 'masonry',
    defaultTypography: 'editorial',
    defaultCardStyle: 'film-strip',
    defaultSectionOrder: ['section-header', 'section-featured', 'section-grid', 'section-about', 'section-contact'],
  },
  {
    id: 'the-gallery',
    name: 'The Gallery',
    tagline: 'Objects of desire.',
    defaultPalette: 'onyx',
    defaultLayout: 'grid-airy',
    defaultTypography: 'modern',
    defaultCardStyle: 'rounded-float',
    defaultSectionOrder: ['section-header', 'section-featured', 'section-grid', 'section-contact'],
  },
];